run:
  concurrency: 8
  timeout: 5m
  issues-exit-code: 2
  tests: true
  skip-dirs:
    - scripts/external_libs
  skip-dirs-use-default: false

  skip-files:
    - ".*\\.yml"
    - ".gitignore"
    - "Makefile"
  modules-download-mode: readonly
  allow-parallel-runners: false
  go: '1.20'

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asciicheck
    - bodyclose
    - asasalint
    - bidichk
    - containedctx
    - contextcheck
    - dupl
    - dupword
    - durationcheck
    - errname
    - errorlint
    - errchkjson
    - execinquery
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gosec
    - importas
    - lll
    - mirror
    - misspell
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tagalign
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck

linters-settings:
  revive:
    rules:
      - name: var-naming
        disabled: true